# .github/workflows/epub-anno-vocab.yml
name: CI (Annotation Model)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "epub34/annotations/**"
      - "common/**"
  push:
    branches: [main]
    paths:
      - "epub34/annotations/**"
      - "common/**"

jobs:
  main:
    name: Publish EPUB Annotations 1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub34/annotations/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_ANNO }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-pm-wg/2023Oct/0028.html
          W3C_BUILD_OVERRIDE: |
             shortName: epub-anno-10
             specStatus: WD
