# .github/workflows/epub-anno-vocab.yml
name: CI (Annotation UCR)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "wg-notes/annotations-ucr/**"
      - "common/**"
  push:
    branches: [main]
    paths:
      - "wg-notes/annotations-ucr/**"
      - "common/**"

jobs:
  main:
    name: Publish EPUB Annotations Use Cases and Requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: wg-notes/annotations-vocab/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_ANNO_UCR }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-pm-wg/2023Oct/0028.html
          W3C_BUILD_OVERRIDE: |
             shortName: epub-anno-ucr
             specStatus: NOTE
