# .github/workflows/epub-34.yml
name: CI (EPUB 3.4)
on:
  pull_request:
    paths: 
      - "epub34/authoring/**"
      - "epub34/acknowledgements.html"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "epub34/authoring/**"
      - "epub34/acknowledgements.html"
      - "common/**"
jobs:
  main:
    name: Publish EPUB 3.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub34/authoring/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_CONTENT }}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/03/13-pmwg-minutes.html#d175
          W3C_BUILD_OVERRIDE: |
             shortName: epub-34
             specStatus: REC
