# .github/workflows/epub-a11-tech-12.yml
name: CI (EPUB Accessibility Techniques)
on:
  pull_request:
    paths: 
      - "epub34/a11y-tech/**"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "epub34/a11y-tech/**"
      - "common/**"
jobs:
  main:
    name: Publish EPUB Accessibility Techniques 1.2 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub34/a11y-tech/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_A11Y_TECH }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-pm-wg/2023Oct/0028.html
          W3C_BUILD_OVERRIDE: |
             shortName: epub-a11y-tech-12
             specStatus: NOTE
